### PR TITLE
Update to use latest Titian Mosaic FreezerManagement 8.7 AMI

### PR DESCRIPTION
**Pull request by KrisDTitian**
This pull request is an update to the latest 8.7 Titian Mosaic FreezerManagement AMI's for use with aws-quickstart.

### CODE REVIEW

**Comment by KrisDTitian** [comment]
For the failing Merge Conflict evaluation, this appears to be between the branch and main with contains the new AMI values.
Please would someone be able to resolve these conflicts to accept the new values from 'Titian_Mosaic_Freezermanagement_8.7'?
Thank you

**Comment by KrisDTitian** [comment]
Hello,
Please would someone be able to take a look at these templates quickly?
Just want to make the latest version of the software available,
Thank you,

**Comment by sshvans** [comment]
@KrisDTitian Can you resolve the conflicts, so that I can test and merge the changes?

**Comment by KrisDTitian** [comment]
@sshvans Hello Shivansh, 
It doesn't appear I have permissions to resolve the conflicts, please would you be able to accept the new values from 'Titian_Mosaic_Freezermanagement_8.7'?
Thank you,

**Comment by sshvans** [comment]
@KrisDTitian You need to merge the changes from upstream main into your branch. You should see the conflicts that you can resolve, commit changes and push it to your branch. That will automatically resolve the conflicts.
Since, I don't have permissions to your fork, I can't resolve conflicts in your branch.

**Comment by KrisDTitian** [comment]
Accidentally closed, will perform tasks as advised and resubmit pull request

**Pull request closed without merging**
